services:
  # frigate: ... # Bring your own Frigate
  # mqtt_broker: ... # mosquitto-eclipse is a good choice
  
  frigate_mqtt:
    build: .
    restart: on-failure:3
    volumes:
      - ./config:/app/config
    #depends_on:
    #  - frigate
    #  - mqtt_broker